language: cpp
dist: xenial
sudo: true
script: ./run-build.sh

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CC='gcc' CXX='g++'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov

    - os: linux
      compiler: clang
      env: CC='clang' CXX='clang++'

after_success:
  - ./create-lcov-report.sh
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
    - LANG="en_US.UTF-8"
